#!/bin/sh

/usr/bin/invoke_app "$@" -C @tool/bin/cc3dCOVID19.sh -t cc3dcovid19 \
                         -u compucell3d-4.2.2 \
                         -w captive \
                         -r none
